"""agrega detalle a pedido

Revision ID: a0618dc89bfd
Revises: 07fc5bb76e9b
Create Date: 2025-12-29 15:28:54.551535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0618dc89bfd'
down_revision = '07fc5bb76e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('producto')

    # ### end Alembic commands ###
