"""tabla auth_users

Revision ID: ebf47ec0c8c5
Revises: a0618dc89bfd
Create Date: 2026-04-18 10:39:48.193776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebf47ec0c8c5'
down_revision = 'a0618dc89bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('inventario_materia_prima')
    op.drop_table('precios_base')
    op.drop_table('inventario_productos')
    op.drop_table('cotizaciones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('tipo_prenda', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('tela', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_estimado', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_estimado', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), server_default=sa.text("'Cotizado'"), nullable=True),
    sa.Column('fecha', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('inventario_productos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('talla', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=False),
    sa.Column('color', mysql.VARCHAR(collation='utf8mb4_general_ci', length=30), nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('precios_base',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo_prenda', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('tela', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('mano_obra', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('urgencia', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('inventario_materia_prima',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('unidad', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('auth_users')
    # ### end Alembic commands ###
